name: Building unity project
on:
 push:
  branches: ["*"]
 pull_request:
  branches: ["*"]

jobs:
 Build-unity-project:
  runs-on: ubuntu-latest
  steps:

    - uses: actions/checkout@v4
      with:
       fetch-depth: 0
       lfs: true

    - uses: actions/cache@v4
      with:
       path: unity_env/Library
       key: Library-LinuxStandalone
       restore-keys: Library-

    - name: Build
      uses: game-ci/unity-builder@v4.2.3
      env:
       UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
       UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
       UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
       unityVersion: auto
       targetPlatform: StandaloneLinux64
       projectPath: unity_env
       buildsPath: python_trainer/build
       buildName: selfDriving

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
       name: Build-LinuxStandalone
       path: python_trainer/build

    - name: Push build
      run: |
       git config --global user.name "github-actions[bot]"
       git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
       git add python_trainer/build
       git status
       git commit --verbose -m "CI: Added unity build"
       git fetch origin
       git rebase --strategy-option=theirs origin/${{ github.head_ref || github.ref_name }}
       git push origin ${{ github.head_ref || github.ref_name }}
