name: Building unity project
on:
 push:
  branches:
   - "*"
   - "!master"
 pull_request:
  branches:
   - "*"
   - "!master"

jobs:
 Build-unity-project:
  runs-on: ubuntu-latest
  steps:

    - uses: actions/checkout@v4
      with:
       fetch-depth: 0
       lfs: true

    - uses: actions/cache@v4
      with:
       path: unity_env/Library
       key: Library
       restore-keys: Library

    - name: Build
      uses: game-ci/unity-builder@v4.2.3
      env:
       UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
       UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
       UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
       unityVersion: auto
       targetPlatform: StandaloneLinux64
       projectPath: unity_env
       buildsPath: python_trainer/build
       buildName: selfDriving

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
       name: Build-LinuxStandalone
       path: python_trainer/build
 
    - name: Pushes to Repository
      uses: tech-thinker/push-to-repo@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.GH_PAT }}
      with:
        user-name: "github-actions[bot]"
        user-email: "github-actions[bot]@users.noreply.github.com"
        source-directory: "python_trainer/build"
        destination-github-username: "ItsOKayCZ"
        destination-repository-name: "self-driving"
        commit-message: "CI: Added build"
        target-branch: ${{ github.head_ref || github.ref_name }}
